name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0' # or your preferred version

      - name: Install dependencies
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Build the application
        run: |
          cd client
          npm run build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl "$RENDER_API_KEY"